title: "Nepal IT Blog - Hemraj Adhikari"
description: "IT tutorials, career guidance from Kathmandu"
url: "https://hemrajadhikari.info.np"
baseurl: ""

theme: minima

author:
  name: Hemraj Adhikari

plugins:
  - jekyll-feed
  - jekyll-sitemap
